### PR TITLE
fix(messaging): Add verification process for the window messaging

### LINKED ISSUE #55: `@webext-core/messaging` errors with `No response` when return value contains function
First, many thanks to the contributors ! Nice project and utils 👍 

I'm using a content script in main world context to dynamically extract "react props" from the whole dom tree for use in another content script not running in main world context.

In console logs the following abreviation stands for
MW: Main World
CS: Content Script

Messenger caller is in a CS without MW context

###  Failing: with error thrown but error message doesn't explain why `No response`

Error message just says
```shell
chunk-ALTBYIMW.js:80 Uncaught (in promise) Error: No response
    at Object.<anonymous> (chunk-ALTBYIMW.js:80:92)
    at Generator.next (<anonymous>)
    at fulfilled (chunk-ALTBYIMW.js:37:19)
```

The issue is that the return value object contains a function.

Example simplified code :

```ts
mainWorldMessenger.onMessage("test", (data) => {
  const props = [
    {
      "className": "ml-md",
      onClick: () => {
      }
    }
  ]

  const ret = {reactProps: props};
  log("return value will be", ret)

  return ret
});
```
image

### Working: messenger func returns with value
```ts
mainWorldMessenger.onMessage("test", (data) => {
  const props = [
    {
      "className": "ml-md",
    }
  ]

  const ret = {reactProps: props};
  log("return value will be", ret)

  return ret
});
```

image

### Solution
Return value can be sanitized.
**An error message from `@webext-core/messaging` explaining why it doesn't return would be nice**

### PR DESCRIPTION
**Pull request by 1natsu172**
fix #55

## Why cause issue

When sending message between windows, if there is data that cannot be serialized, the response will be `null`. This causes a `No response` error. 

### Solution

It needs to be an error that the user can understand. Add a verification process before the browser sends the message to improve this.

### CODE REVIEW

File: packages/messaging/src/generic.ts [hunk 1]
```diff
@@ -109,12 +110,13 @@ export function defineGenericMessanging<
...
       ...args: TSendMessageArgs
     ): Promise<any> {
-      const message: Message<TProtocolMap, TType> = {
+      const _message: Message<TProtocolMap, TType> = {
         id: getNextId(),
         type: type,
         data,
         timestamp: Date.now(),
       };
+      const message = (await config.verifyMessageData?.(_message)) ?? _message;
```
Comment (1natsu172) [inline packages/messaging/src/generic.ts:119]: Verification of this data

```
await sendMessage('getSomething``, { please: "verify this data"});
```

File: packages/messaging/src/generic.ts [hunk 2]
```diff
@@ -150,6 +152,9 @@ export function defineGenericMessanging<
 
           const res = listener(message);
           return Promise.resolve(res)
+            .then(res => {
+              return config.verifyMessageData?.(res) ?? res;
+            })
```
Comment (1natsu172) [inline packages/messaging/src/generic.ts:157]: Verification of this data.

```
onMessage("getSomething", (data) => {
  return { please: "verify this data"}
});
```

**Comment by aklinker1** [comment]
Released in https://github.com/aklinker1/webext-core/releases/tag/messaging-v2.0.3
